/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData edit = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_orders = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData policy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translation = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_fill = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_fill = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_drive = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_thin = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_order = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accept = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_request = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shipping = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
